<?php 

$general = [
    'steel' => 'STEEL',
    'stainlessSteel' => 'STAINLESS STEEL',
    'stainlessSteelBody' => 'The inoxidable steel, known as its durability and resistance to corrosion, is the ideal choice for industrial applications and domestic uses. With its elegant temporal and low maintenance, the inox offers a solution confident and stylish for a wide range of needs, guaranteeing quality and longevity in each application. Discover the excellence of the inox - the perfect combination of robustness and simplicity.',
    'carbon' => 'CARBON',
    'carbonBody' => 'Carbon steel, synonymous with versatility and robustness, stands out as a fundamental material in various industrial applications. With the ability to offer exceptional strength and ease of molding, carbon steel is the trusted choice for robust structures and critical components. Discover the strength and adaptability of carbon steel, driving excellence across diverse sectors.',
    'galvanized' => 'GALVANIZED',
    'galvanizedBody' => 'Galvanized steel, synonymous with durability and corrosion resistance, stands out as a prime choice for a variety of applications. Its zinc layer provides an effective protective barrier, ensuring longevity even in challenging environments. Discover the reliability of galvanized steel, the ideal solution for robust, long-lasting structures.',
    'flanges' => 'FLANGES AND CONNECTIONS',
    'flangesBody' => 'Elevating the robustness of your operations, our steel flanges and fittings are the ultimate choice to ensure structural integrity and superior performance. Designed to withstand the most demanding industrial demands, our solutions offer exceptional durability and millimeter precision, ensuring a reliable connection in every application. Discover the strength of quality in steel flanges and connections, fundamental to the continued success of your projects.',
    'metal' => 'METAL',
    'bronze' => 'BRONZE',
    'bronzeBody' => 'The engineering bronze, the perfect fusion of resistance and precision, is the superior option for demanding industrial applications. Recognized for its resistance to wear, corrosion and its excellent mechanical properties, our engineering bronze offers solid solutions for critical components. Discover the power of material innovation with engineering excellence, shaping the future of industrial excellence.',
    'copper' => 'COPPER',
    'copperBody' => 'Engineering copper, the embodiment of efficient conduction and durability, stands out as the prime choice for high-performance electrical and mechanical applications. Recognized for its exceptional conductivity and corrosion resistance, our engineered copper offers reliable solutions for the most demanding challenges. Discover the excellence of engineering copper, driving innovation and efficiency in your projects.',
    'aluminum' => 'ALUMINUM',
    'aluminumBody' => 'Engineering aluminum, embodying lightness and strength, stands out as the ideal choice for innovations in design and durability. Recognized for its versatility, our engineering aluminum offers exceptional solutions for aerospace, automotive and structural applications. Discover the unlimited potential of engineering aluminum, boosting efficiency and performance in your projects.',
    'brass' => 'BRASS',
    'brassBody' => 'El latón de ingeniería, símbolo de versatilidad y resistencia, se destaca como la opción premium para aplicaciones que exigen durabilidad y estética refinada. Combinando la durabilidad del cobre y la maleabilidad del zinc, nuestro latón de ingeniería ofrece soluciones excepcionales para componentes precisos y elegantes. Descubra la sofisticación y el rendimiento incomparables del latón de ingeniería, llevando sus proyectos a un nuevo nivel.',
    'plastic' => 'PLASTIC',
    'teflon' => 'TEFLON',
    'teflonBody' => 'Polytetrafluoroethylene (PTFE), which is commonly known by its trade name, is synonymous with exceptional strength and low coefficient of friction, stands out as the premium choice for demanding industrial and technological applications. With its unique ability to resist high temperatures and aggressive chemicals, our engineered Teflon offers cutting-edge solutions for components that demand durability and superior performance. Discover the innovation encapsulated in engineering Teflon, driving excellence in advanced engineering.',
    'pa6g' => 'PA6G',
    'pa6gBody' => 'PA6G cast nylon, embodying durability and versatility, stands out as the rugged choice for demanding industrial applications. With exceptional mechanical properties, our cast nylon offers wear resistance, impact absorption and dimensional stability, providing high-performance solutions for precise components. Discover the reliability and innovation encapsulated in PA6G cast nylon, driving excellence in advanced engineering.',
    'pu' => 'PU',
    'puBody' => 'Engineering polyurethane, a symbol of versatility and resistance, stands out as the innovative choice for applications that demand durability and superior performance. With its exceptional adaptability, our engineered polyurethane offers customized solutions for precise components in diverse industrial sectors. Discover the exceptional flexibility and strength of polyurethane, driving efficiency and innovation in your projects.',
    'celeron' => 'CELERON',
    'celeronBody' => 'The engineered Celeron, synonymous with electrical and mechanical strength, stands out as a premium choice for thermal insulation and electrical applications. With its composition of phenolic resin-impregnated fibers, our Celeron offers exceptional durability and dimensional stability, providing reliable solutions for challenging environments. Discover the innovation and reliability encapsulated in the engineering Celeron, driving excellence in insulation and electrical components.',
    'rubber' => 'RUBBER',
    'nbr' => 'NBR',
    'nbrBody' => 'Engineered NBR, the embodiment of strength and durability, stands out as a premium choice for applications that demand exceptional performance in challenging environments. With its robust mechanical properties and resistance to various environmental factors, our engineered NBR offers reliable solutions for sealing, insulation and industrial components. Discover the excellence encapsulated in NBR engineering, driving reliability and efficiency in your projects.',
    'silicone' => 'SILICONE',
    'siliconeBody' => 'Engineering silicone, synonymous with versatility and thermal resistance, stands out as the leading choice for industrial and medical applications. With exceptional extreme temperature resistance and flexibility properties, our engineered silicone provides reliable solutions for sealing, insulation and advanced medical devices. Discover the innovation encapsulated in engineering silicone, elevating excellence in design and performance.',
    'geomembrane' => 'GEOMEMBRANE',
    'geomembraneBody' => 'The engineering geomembrane, a symbol of efficient waterproofing and durability, stands out as the primary choice for geotechnical and containment projects. With its exceptional resistance to chemical agents and weathering, our geomembrane offers reliable solutions for lining ponds, landfills and reservoirs. Discover the trust and security built into engineered geomembrane, driving quality and sustainability in your applications.',
    'neoprene' => 'NEOPRENE',
    'neopreneBody' => 'Neoprene for industrial use, synonymous with resistance and versatility, stands out as the ideal choice for demanding applications. With its exceptional durability and resistance to oils, solvents and weathering, our industrial neoprene offers reliable solutions for sealing, insulation and wear-resistant components. Discover excellence encapsulated in industrial grade neoprene, boosting performance and reliability in industrial environments',
    'title' => 'STEELPLAST',
    'home' => 'HOME',
    'products' => 'PRODUCTS',
    'about' => 'ABOUT',
    'values' => 'COMPANY VALUES',
    'contact' => 'CONTACT',
    'language' => 'LANGUAGE',
    'aboutBody' => 'Welcome to Steelplast, an organization dedicated to excellence and innovation. Since our foundation in 2000, we have tirelessly worked to offer exceptional solutions and build solid relationships with our clients, collaborators, and partners.',
    'contactBody' => 'Fill out the form and we will return soon.',
    'companyValues' => 'Uncompromising Quality: We commit to offering only engineering materials that meet the highest standards of quality, ensuring the satisfaction and trust of our clients.',
    'companyValues2' => 'Continuous Innovation: We stimulate creativity and the constant search for innovative solutions, aiming to improve our processes and anticipate market needs.',
    'companyValues3' => 'Global Connection: We believe in the strength of global connections and the importance of integrating Brazil into the international scenario, promoting an exchange of knowledge and technologies.',
    'companyValues4' => 'Trustworthy Relationships: We value transparency and integrity in all our relationships, cultivating long-term partnerships based on mutual trust and respect.',
    'companyValues5' => 'Personalized Service: We prioritize customer satisfaction, offering personalized and consultative service, adapting to the specific needs of each project.',
    'toastTime' => 'now',
    'toastTitle' => 'Hi, I am the Steel-bot!',
    'toastBody' => 'Accessing the site, you agree with the privacy rules.',
    'formBtn' => 'Budget',
    'formQuestion' => 'Does your company already imports?',
    'formAnswer' => 'Yes, I am importing!',
    'formAnswer2' => 'I do not import!',
    'formResponse' => 'Sorry, but at the moment we only serve businesses that are licensed with the Federal Revenue Administration to import materials.',
    'form' => 'Form',
    'close' => 'Close',
    'loading' => 'Loading...',
    'thanks' => 'Thank you!',
    'error' => 'An error occurred while sending the form. Please try again later.',
    'send' => 'Send',
    'companyName' => 'Company name',
    'companyPhone' => 'Company phone',
    'message' => 'Message',
    'mission' => 'Provide innovative engineering solutions and high-quality materials, connecting Brazil to the world. We seek to drive the success of our customers by promoting excellence in all aspects of our operations.',
    'missionTitle' => 'Our Mission',
];

$products = [
    'stainlessSteel' => [
        'workWith' => 'We work with Stainless Steel 304 and 304L in the following formats',
        'norms' => 'ASTM A240 and A240M standards',
        'bars' => 'Diameters from 3mm to 200mm by 1 meter and 3 meters.',
        'barsTitle' => 'Bars',
        'tubes' => 'Diameters from 6mm to 200mm by 1 meter and 3 meters.',
        'tubesTitle' => 'Tubes',
        'plate' => 'Thickness from 0.40mm to 25.4mm by 1000 x 2000mm and 1000 x 3000mm',
        'plateTitle' => 'Plates',
        'coil' => 'Thickness from 0.30mm to 3mm with a width of 600mm',
        'coilTitle' => 'Coils',
    ],
    'carbon' => [
        'workWith' => 'We work with carbon steel 4140, 1045, 1018, 1080, and 1095',
        'norms' => 'ASTM A322, A108, A36, A516, and A106 standards',
        'bars' => 'Thickness from 0.40mm to 25.4mm by 1000 x 2000mm and 1000 x 3000mm',
        'barsTitle' => 'Bars',
        'tubes' => 'Diameters from 10.2mm to 400mm by 3 and 6 meters',
        'tubesTitle' => 'Tubes',
        'plate' => 'Thickness from 0.40mm to 25.4mm by 1000 x 2000mm and 1000 x 3000mm',
        'plateTitle' => 'Plates',
        'coil' => 'Thickness from 0.30mm to 5mm with a width of 600mm',
        'coilTitle' => 'Coils',
    ],
    'galvanized' => [
        'workWith' => '',
        'norms' => 'ASTM A653/A653M standards',
        'bars' => 'Diameters from 3mm to 200mm by 1 meter and 3 meters.',
        'barsTitle' => 'Bars',
        'tubes' => 'Diameters from 12mm to 400mm by 3 and 6 meters',
        'tubesTitle' => 'Tubes',
        'plate' => 'Thickness from 0.40mm to 25.4mm by 1000 x 2000mm and 1000 x 3000mm',
        'plateTitle' => 'Plates',
        'coil' => 'Thickness from 0.30mm to 5mm with a width of 600mm',
        'coilTitle' => 'Coils',
    ],
    'flanges' => [
        'workWith' => '',
        'norms' => 'ASTM standards related to flanges and steel fittings vary depending on the specific type and application. Here are some common standards:',
        'normsLoop' => [
            'Carbon steel flanges: ASTM A105/A105M',
            'Stainless steel flanges: ASTM A182/A182M',
            'Low alloy steel flanges: ASTM A182/A182M'
        ],
        'connections' => [
            'Forged carbon and alloy steel fittings: ASTM A105/A105M',
            'Forged stainless steel fittings: ASTM A182/A182M',
            'Carbon and alloy steel tube fittings: ASTM A234/A234M'
        ],
        'connectionsTitle' => 'Connections',
    ],
    'bronze' => [
        'workWith' => '',
        'norms' => 'ASTM B584/584M, B505/B505, SAE J461, and J462 standards',
        'bars' => 'Diameters from 6.35mm to 400mm by 1000mm or 3000mm.',
        'barsTitle' => 'Bars',
        'tubes' => 'Diameters from 76.20mm to 127mm by 1000mm or 3000mm.',
        'tubesTitle' => 'Tubes',
        'plate' => 'Thickness from 1.5mm to 3.17mm with a width of 290mm or 580mm.',
        'plateTitle' => 'Plates',
        'coil' => 'Thickness from 0.10mm to 1.40mm with a width of 290mm or 580mm.',
        'coilTitle' => 'Coils',
    ],
    'copper' => [
        'workWith' => '',
        'norms' => 'ASTM B5/B5M, B187/B187M, B152/B152M, and B133/B133M standards',
        'bars' => 'Diameters from 3.17mm to 304.80mm by 1000mm or 3000mmm.',
        'barsTitle' => 'Bars',
        'tubes' => 'Diameters from 76.20mm to 127mm by 1000mm or 3000mm.',
        'tubesTitle' => 'Tubes',
        'plate' => 'Thickness from 1mm to 3.17mm by 600 x 1200mm or 1000 x 2000mm.',
        'plateTitle' => 'Plates',
        'coil' => 'Thickness from 0.10mm to 1.40mm with a width of 305mm or 600mm.',
        'coilTitle' => 'Coils',
    ],
    'aluminum' => [
        'workWith' => '',
        'norms' => 'ASTM B221, B209, AMS 4027 standards',
        'bars' => 'Diameters from 6.35mm to 165.10mm by 1000mm or 3000mm.',
        'barsTitle' => 'Bars',
        'tubes' => 'Diameters from 9.52mm to 168.28mm by 1000mm or 3000mm.',
        'tubesTitle' => 'Tubes',
        'plate' => 'Thickness from 5mm to 203.2mm by 1000 x 2000mm or 1000 x 3000mm.',
        'plateTitle' => 'Plates',
        'coil' => 'Thickness from 0.30mm to 3mm with a width of 305mm or 600mm.',
        'coilTitle' => 'Coils',
    ],
    'brass' => [
        'workWith' => '',
        'norms' => 'ASTM B16, B124, B135/B135M standards',
        'bars' => 'Diameters from 28.57mm to 203.20mm by 1000mm or 3000mm.',
        'barsTitle' => 'Bars',
        'tubes' => 'Diameters from 6.35mm to 203.20mm by 1000mm or 3000mm.',
        'tubesTitle' => 'Tubes',
        'plate' => 'Thickness from 3.97mm to 76.20mm by 600mm x 1200mm or 1000 x 2000mm.',
        'plateTitle' => 'Plates',
        'coil' => 'Thickness from 0.10mm to 3mm by 305mm or 600mm.',
        'coilTitle' => 'Coils',
    ],
    'teflon' => [
        'workWith' => '',
        'norms' => 'ASTM D1710 standards',
        'barsTitle' => 'Bars',
        'bars' => 'Diameters from 10mm to 500mm by 1 meter and 3 meters.',
        'tubesTitle' => 'Tubes',
        'tubes' => 'Diameters from 50mm to 200mm by 1 meter and 3 meters.',
        'plateTitle' => 'Plates',
        'plate' => 'Thickness from 1mm to 100mm by 1000 x 1000mm and 1000 x 2000mm.'
    ],
    'pa6g' => [
        'barsTitle' => 'Bars',
        'bars' => 'Diameters from 60mm to 500mm by 1000 and 3000mm.',
        'tubesTitle' => 'Tubes',
        'tubes' => 'Diameters from 80mm to 200mm by 1000 and 3000mm.',
        'plateTitle' => 'Plates',
        'plate' => 'Thickness from 10mm to 100mm by 1000 x 2000mm and 1000 x 3000mm'
    ],
    'pu' => [
        'barsTitle' => 'Bars',
        'bars' => 'Diameters from 10mm to 300mm by 300mm',
        'tubesTitle' => 'Tubes',
        'tubes' => 'Diameters from 50mm to 300mm by 300mm.',
        'plateTitle' => 'Plates',
        'plate' => 'Thickness from 10mm to 100mm by 500 x 500mm'
    ],
    'celeron' => [
        'barsTitle' => 'Bars',
        'bars' => 'Diameters from 6mm to 200mm by 1000mm',
        'tubesTitle' => 'Tubes',
        'tubes' => 'Diameters from 9.5mm to 300mm by 1000mm',
        'plateTitle' => 'Plates',
        'plate' => 'Thickness from 0.6mm to 100mm by 1000 x 2000mm'
    ]
];