<?php

$general = [
    'steel' => 'ACIER',
    'stainlessSteel' => 'ACIER INOXYDABLE',
    'stainlessSteelBody' => "L'acier inoxydable, connu pour sa durabilité et sa résistance à la corrosion, est le choix idéal pour les applications industrielles et les usages domestiques. Avec son élégance intemporelle et sa faible maintenance, l'inox offre une solution fiable et élégante pour une large gamme de besoins, garantissant qualité et longévité dans chaque application. Découvrez l'excellence de l'inox - la combinaison parfaite de robustesse et de simplicité.",
    'carbon' => 'CARBONE',
    'carbonBody' => "L'acier au carbone, synonyme de polyvalence et de robustesse, se distingue comme un matériel fondamental dans diverses applications industrielles. Avec la capacité d'offrir une résistance exceptionnelle et une facilité de moulage, l'acier au carbone est le choix de confiance pour les structures robustes et les composants critiques. Découvrez la force et l'adaptabilité de l'acier au carbone, moteur d'excellence dans divers secteurs.",
    'galvanized' => 'GALVANISÉ',
    'galvanizedBody' => "L'acier galvanisé, synonyme de durabilité et de résistance à la corrosion, se distingue comme un choix privilégié pour une variété d'applications. Sa couche de zinc fournit une barrière protectrice efficace, assurant une longévité même dans des environnements difficiles. Découvrez la fiabilité de l'acier galvanisé, la solution idéale pour des structures robustes et durables.",
    'flanges' => 'BRIDES ET RACCORDS',
    'flangesBody' => "Rehaussant la robustesse de vos opérations, nos brides et raccords en acier sont le choix ultime pour assurer l'intégrité structurelle et une performance supérieure. Conçus pour résister aux exigences industrielles les plus exigeantes, nos solutions offrent une durabilité exceptionnelle et une précision millimétrique, assurant une connexion fiable dans chaque application. Découvrez la force de la qualité dans les brides et raccords en acier, fondamentaux pour le succès continu de vos projets.",
    'metal' => 'MÉTAL',
    'bronze' => 'BRONZE',
    'bronzeBody' => "Le bronze d'ingénierie, la fusion parfaite de résistance et de précision, est le choix supérieur pour des applications industrielles exigeantes. Reconnu pour sa résistance à l'usure, à la corrosion et ses excellentes propriétés de usinage, notre bronze d'ingénierie offre des solutions solides pour des composants critiques. Découvrez le pouvoir de l'innovation des matériaux avec le bronze d'ingénierie, façonnant l'avenir de l'excellence industrielle.",
    'copper' => 'CUIVRE',
    'copperBody' => "Le cuivre d'ingénierie, l'incarnation de la conduction efficace et de la durabilité, se distingue comme le meilleur choix pour des applications électriques et mécaniques de haute performance. Reconnu pour sa conductivité exceptionnelle et sa résistance à la corrosion, notre cuivre d'ingénierie offre des solutions fiables pour les défis les plus exigeants. Découvrez l'excellence du cuivre d'ingénierie, propulsant l'innovation et l'efficacité dans vos projets.",
    'aluminum' => 'ALUMINIUM',
    'aluminumBody' => "L'aluminium d'ingénierie, personnifiant la légèreté et la résistance, se distingue comme un choix idéal pour les innovations en matière de conception et de durabilité. Reconnu pour sa versatilité, notre aluminium d'ingénierie offre des solutions exceptionnelles pour des applications aérospatiales, automobiles et structurelles. Découvrez le potentiel illimité de l'aluminium d'ingénierie, propulsant l'efficacité et la performance de nos projets.",
    'brass' => 'LAITON',
    'brassBody' => "Le laiton d'ingénierie, symbole de versatilité et de résistance, se distingue comme le choix premium pour des applications exigeant durabilité et esthétique raffinée. Combinant la durabilité du cuivre et la malléabilité du zinc, notre laiton d'ingénierie offre des solutions exceptionnelles pour des composants précis, élégants. Découvrez la sophistication et la performance incomparables du laiton d'ingénierie, élevant vos projets à un nouveau niveau.",
    'plastic' => 'PLASTIQUE',
    'teflon' => 'TEFLON',
    'teflonBody' => "Le politétrafluoroéthylène (PTFE), communément connu sous son nom commercial, est synonyme de résistance exceptionnelle et de faible coefficient de friction, et se distingue comme le meilleur choix pour des applications industrielles et technologiques exigeantes. Avec sa capacité unique à résister à des températures élevées et à des produits chimiques agressifs, notre teflon conçu offre des solutions d'avant-garde pour des composants exigeant durabilité et performance supérieure. Découvrez l'innovation contenue dans le teflon d'ingénierie, propulsant l'excellence en ingénierie avancée.",
    'pa6g' => 'PA6G',
    'pa6gBody' => "Le nylon coulé PA6G, incorporant durabilité et versatilité, se distingue comme le choix résistant pour des applications industrielles exigeantes. Avec des propriétés mécaniques exceptionnelles, notre nylon coulé offre résistance à l'usure, absorption des chocs et stabilité dimensionnelle, fournissant des solutions de haute performance pour des composants précis. Découvrez la fiabilité et l'innovation encapsulées dans le nylon coulé PA6G, propulsant l'excellence en ingénierie avancée.",
    'pu' => 'PU',
    'puBody' => "Le polyuréthane d'ingénierie, symbole de versatilité et de résistance, se distingue comme l'option innovante pour des applications exigeant durabilité et performance supérieure. Avec son adaptabilité exceptionnelle, notre polyuréthane conçu offre des solutions personnalisées pour des composants précis dans divers secteurs industriels. Découvrez l'exceptionnelle flexibilité et résistance du polyuréthane, propulsant l'efficacité et l'innovation dans vos projets.",
    'celeron' => 'CÉLÉRON',
    'celeronBody' => "Le Celeron d'ingénierie, synonyme de résistance électrique et mécanique, se distingue comme une option premium pour l'isolation thermique et des applications électriques. Avec sa composition de fibres imprégnées de résine phénolique, notre Celeron offre une durabilité et une stabilité dimensionnelle exceptionnelles, fournissant des solutions fiables pour des environnements exigeants. Découvrez l'innovation et la fiabilité contenues dans le Celeron d'ingénierie, propulsant l'excellence dans l'isolation et les composants électriques.",
    'rubber' => 'CAOUTCHOUC',
    'nbr' => 'NBR',
    'nbrBody' => "Le NBR d'ingénierie, l'incarnation de la force et de la durabilité, se distingue comme un choix premium pour des applications exigeant une performance exceptionnelle dans des environnements difficiles. Avec ses propriétés mécaniques robustes et sa résistance à divers facteurs environnementaux, notre NBR d'ingénierie offre des solutions fiables pour l'étanchéité, l'isolation et les composants industriels. Découvrez l'excellence encapsulée dans l'ingénierie NBR, conduisant la fiabilité et l'efficacité dans vos projets.",
    'silicone' => 'SILICONE',
    'siliconeBody' => "Le silicone d'ingénierie, synonyme de polyvalence et de résistance thermique, se distingue comme le choix principal pour les applications industrielles et médicales. Avec une résistance exceptionnelle aux températures extrêmes et des propriétés de flexibilité, notre silicone d'ingénierie offre des solutions fiables pour l'étanchéité, l'isolation et les dispositifs médicaux avancés. Découvrez l'innovation encapsulée dans le silicone d'ingénierie, élevant l'excellence dans la conception et la performance.",
    'geomembrane' => 'GÉOMEMBRANE',
    'geomembraneBody' => "La géomembrane d'ingénierie, un symbole d'imperméabilisation efficace et de durabilité, se distingue comme le choix principal pour les projets géotechniques et de confinement. Avec sa résistance exceptionnelle aux agents chimiques et aux intempéries, notre géomembrane offre des solutions fiables pour le revêtement d'étangs, de décharges et de réservoirs. Découvrez la confiance et la sécurité intégrées dans la géomembrane d'ingénierie, conduisant la qualité et la durabilité dans vos applications.",
    'neoprene' => 'NÉOPRÈNE',
    'neopreneBody' => "Le néoprène pour utilisation industrielle, synonyme de résistance et de polyvalence, se distingue comme le choix idéal pour des applications exigeantes. Avec sa durabilité exceptionnelle et sa résistance aux huiles, solvants et intempéries, notre néoprène industriel offre des solutions fiables pour l'étanchéité, l'isolation et les composants résistants à l'usure. Découvrez l'excellence encapsulée dans le néoprène de qualité industrielle, améliorant la performance et la fiabilité dans les environnements industriels.",
    'title' => 'STEELPLAST',
    'home' => 'ACCUEIL',
    'products' => 'PRODUITS',
    'about' => 'PROPOS',
    'values' => 'VALEURS D\'ENTREPRISE',
    'contact' => 'CONTACT',
    'language' => 'LANGUE',
    'aboutBody' => "Bienvenue chez Steelplast, une organisation dédiée à l'excellence et à l'innovation. Depuis notre fondation en 2000, nous avons travaillé sans relâche pour offrir des solutions exceptionnelles et établir des relations solides avec nos clients, collaborateurs et partenaires.",
    'contactBody' => "Remplissez le formulaire et nous reviendrons vers vous bientôt.",
    'companyValues' => "Qualité sans compromis : Nous nous engageons à offrir uniquement des matériaux d'ingénierie qui répondent aux normes de qualité les plus élevées, assurant la satisfaction et la confiance de nos clients.",
    'companyValues2' => "Innovation Continue : Nous stimulons la créativité et la recherche constante de solutions innovantes, visant à améliorer nos processus et anticiper les besoins du marché.",
    'companyValues3' => "Connexion Globale : Nous croyons en la force des connexions mondiales et l'importance d'intégrer le Brésil dans le scénario international, en promouvant un échange de connaissances et de technologies.",
    'companyValues4' => "Relations de confiance : Nous valorisons la transparence et l'intégrité dans toutes nos relations, cultivant des partenariats à long terme basés sur la confiance et le respect mutuels.",
    'companyValues5' => "Service Personnalisé : Nous donnons la priorité à la satisfaction du client, offrant un service personnalisé et consultatif, s'adaptant aux besoins spécifiques de chaque projet.",
    'toastTime' => 'maintenant',
    'toastTitle' => 'Salut, je suis le Steel-bot !',
    'toastBody' => 'En accédant au site, vous acceptez les règles de confidentialité.',
    'formBtn' => 'Devis',
    'formQuestion' => 'Votre entreprise importe-t-elle déjà ?',
    'formAnswer' => 'Oui, j\'importe !',
    'formAnswer2' => 'Je n\'importe pas !',
    'formResponse' => 'Désolé, mais à l\'instant nous servons uniquement les entreprises qui sont autorisées par l\'Administration Fédérale des Recettes à importer des matériaux.',
    'form' => 'Formulaire',
    'close' => 'Fermer',
    'loading' => 'Chargement...',
    'thanks' => 'Merci !',
    'error' => 'Une erreur est survenue lors de l\'envoi du formulaire. Veuillez réessayer plus tard.',
    'send' => 'Envoyer',
    'companyName' => 'Nom de l\'entreprise',
    'companyPhone' => 'Téléphone de l\'entreprise',
    'message' => 'Message',
    'mission' => 'Fournir des solutions d\'ingénierie innovantes et des matériaux de haute qualité, connectant le Brésil au monde. Nous cherchons à conduire le succès de nos clients en promouvant l\'excellence dans tous les aspects de nos opérations.',
    'missionTitle' => 'Notre Mission',
];

$products = [
    'stainlessSteel' => [
        'workWith' => 'Nous travaillons avec de l\'acier inoxydable 304 et 304L dans les formats suivants',
        'norms' => 'Normes ASTM A240 et A240M',
        'bars' => 'Diamètres de 3mm à 200mm par 1 mètre et 3 mètres.',
        'barsTitle' => 'Barres',
        'tubes' => 'Diamètres de 6mm à 200mm par 1 mètre et 3 mètres.',
        'tubesTitle' => 'Tubes',
        'plate' => 'Épaisseur de 0,40mm à 25,4mm par 1000 x 2000mm et 1000 x 3000mm',
        'plateTitle' => 'Plaques',
        'coil' => 'Épaisseur de 0,30mm à 3mm avec une largeur de 600mm',
        'coilTitle' => 'Bobines',
    ],
    'carbon' => [
        'workWith' => 'Nous travaillons avec de l\'acier au carbone 4140, 1045, 1018, 1080 et 1095',
        'norms' => 'Normes ASTM A322, A108, A36, A516 et A106',
        'bars' => 'Épaisseur de 0,40mm à 25,4mm par 1000 x 2000mm et 1000 x 3000mm',
        'barsTitle' => 'Barres',
        'tubes' => 'Diamètres de 10,2mm à 400mm par 3 et 6 mètres',
        'tubesTitle' => 'Tubes',
        'plate' => 'Épaisseur de 0,40mm à 25,4mm par 1000 x 2000mm et 1000 x 3000mm',
        'plateTitle' => 'Plaques',
        'coil' => 'Épaisseur de 0,30mm à 5mm avec une largeur de 600mm',
        'coilTitle' => 'Bobines',
    ],
    'galvanized' => [
        'workWith' => '',
        'norms' => 'Normes ASTM A653/A653M',
        'bars' => 'Diamètres de 3mm à 200mm par 1 mètre et 3 mètres.',
        'barsTitle' => 'Barres',
        'tubes' => 'Diamètres de 12mm à 400mm par 3 et 6 mètres',
        'tubesTitle' => 'Tubes',
        'plate' => 'Épaisseur de 0,40mm à 25,4mm par 1000 x 2000mm et 1000 x 3000mm',
        'plateTitle' => 'Plaques',
        'coil' => 'Épaisseur de 0,30mm à 5mm avec une largeur de 600mm',
        'coilTitle' => 'Bobines',
    ],
    'flanges' => [
        'workWith' => '',
        'norms' => 'Les normes ASTM relatives aux brides et aux raccords en acier varient en fonction du type spécifique et de l\'application. Voici quelques normes courantes :',
        'normsLoop' => [
            'Brides en acier au carbone : ASTM A105/A105M',
            'Brides en acier inoxydable : ASTM A182/A182M',
            'Brides en acier à faible alliage : ASTM A182/A182M'
        ],
        'connections' => [
            'Raccords forgés en acier au carbone et en acier allié : ASTM A105/A105M',
            'Raccords forgés en acier inoxydable : ASTM A182/A182M',
            'Raccords de tube en acier au carbone et en acier allié : ASTM A234/A234M'
        ],
        'connectionsTitle' => 'Connexions',
    ],
    'bronze' => [
        'workWith' => '',
        'norms' => 'Normes ASTM B584/584M, B505/B505, SAE J461 et J462',
        'bars' => 'Diamètre de 6,35mm à 400mm par 1000mm ou 3000mm.',
        'barsTitle' => 'Barres',
        'tubes' => 'Diamètre de 76,20mm à 127mm par 1000mm ou 3000mm.',
        'tubesTitle' => 'Tubes',
        'plate' => 'Épaisseur de 1,5mm à 3,17mm avec une largeur de 290mm ou 580mm.',
        'plateTitle' => 'Plaques',
        'coil' => 'Épaisseur de 0,10mm à 1,40mm avec une largeur de 290mm ou 580mm.',
        'coilTitle' => 'Bobines',
    ],
    'copper' => [
        'workWith' => '',
        'norms' => 'Normes ASTM B5/B5M, B187/B187M, B152/B152M et B133/B133M',
        'bars' => 'Diamètre de 3,17mm à 304,80mm par 1000mm ou 3000mmm.',
        'barsTitle' => 'Barres',
        'tubes' => 'Diamètre de 76,20mm à 127mm par 1000mm ou 3000mm.',
        'tubesTitle' => 'Tubes',
        'plate' => 'Épaisseur de 1mm à 3,17mm  par 600 x 1200mm ou 1000 x 2000mm.',
        'plateTitle' => 'Plaques',
        'coil' => 'Épaisseur de 0,10mm à 1,40mm avec une largeur de 305mm ou 600mm.',
        'coilTitle' => 'Bobines',
    ],
    'aluminum' => [
        'workWith' => '',
        'norms' => 'Normes ASTM B221, B209, AMS 4027',
        'bars' => 'Diamètre de  6,35mm à 165,10mm par 1000mm ou 3000mm.',
        'barsTitle' => 'Barres',
        'tubes' => 'Diamètre de 9,52mm à 168,28mm par 1000mm ou 3000mm.',
        'tubesTitle' => 'Tubes',
        'plate' => 'Épaisseur de 5mm à 203,2mm par 1000 x 2000mm ou 1000 x 3000mm.',
        'plateTitle' => 'Plaques',
        'coil' => 'Épaisseur de 0,30mm à 3mm avec une largeur de 305mm ou 600mm.',
        'coilTitle' => 'Bobines',
    ],
    'brass' => [
        'workWith' => '',
        'norms' => 'Normes ASTM B16, B124, B135/B135M',
        'bars' => 'Diamètre de 28,57mm à 203,20mm par 1000mm ou 3000mm.',
        'barsTitle' => 'Barres',
        'tubes' => 'Diamètre de 6,35mm à 203,20mm par 1000mm ou 3000mm.',
        'tubesTitle' => 'Tubes',
        'plate' => 'Épaisseur de 3,97mm à 76,20mm de 600mm x 1200mm ou 1000 x 2000mm.',
        'plateTitle' => 'Plaques',
        'coil' => 'Épaisseur de 0,10mm à 3mm par 305mm ou 600mm.',
        'coilTitle' => 'Bobines',
    ],
    'teflon' => [
        'workWith' => '',
        'norms' => 'Norme ASTM D1710',
        'barsTitle' => 'Barres',
        'bars' => 'Diamètres de 10mm à 500mm par 1 mètre et 3 mètres.',
        'tubesTitle' => 'Tubes',
        'tubes' => 'Diamètres de 50mm à 200mm par 1 mètre et 3 mètres.',
        'plateTitle' => 'Plaques',
        'plate' => 'Épaisseur de 1 mm à 100mm par 1000 x 1000mm et 1000 x 2000mm.'
    ],
    'pa6g' => [
        'barsTitle' => 'Barres',
        'bars' => 'Diamètres de 60mm à 500mm par 1000 et 3000mm.',
        'tubesTitle' => 'Tubes',
        'tubes' => 'Diamètres de 80mm à 200mm par 1000 et 3000mm.',
        'plateTitle' => 'Plaques',
        'plate' => 'Épaisseur de 10 mm à 100mm par 1000 x 2000mm et 1000 x 3000mm'
    ],
    'pu' => [
        'barsTitle' => 'Barres',
        'bars' => 'Diamètres de 10mm à 300mm par 300mm',
        'tubesTitle' => 'Tubes',
        'tubes' => 'Diamètres de 50mm à 300mm par 300mm.',
        'plateTitle' => 'Plaques',
        'plate' => 'Épaisseur de 10 mm à 100mm par 500 x 500mm'
    ],
    'celeron' => [
        'barsTitle' => 'Barres',
        'bars' => 'Diamètres de 6mm à 200mm par 1000mm',
        'tubesTitle' => 'Tubes',
        'tubes' => 'Diamètres de 9,5mm à 300mm par 1000mm',
        'plateTitle' => 'Plaques',
        'plate' => 'Épaisseur de 0,6 mm à 100mm par 1000 x 2000mm'
    ]
];