<?php 

$general = [
    'steel' => 'ACO',
    'stainlessSteel' => 'INOX',
    'stainlessSteelBody' => 'O aço inoxidável, conhecido por sua durabilidade e resistência à corrosão, é a escolha ideal para aplicações industriais e domésticas. Com sua elegância atemporal e baixa manutenção, o aço inox oferece uma solução confiável e esteticamente agradável para uma variedade de necessidades, garantindo qualidade e longevidade em cada aplicação. Descubra a excelência do aço inox – a combinação perfeita de robustez e sofisticação.',
    'carbon' => 'CARBONO',
    'carbonBody' => 'O aço carbono, sinônimo de versatilidade e robustez, destaca-se como um material fundamental em diversas aplicações industriais. Com a capacidade de oferecer resistência excepcional e facilidade de moldagem, o aço carbono é a escolha confiável para estruturas robustas e componentes essenciais. Descubra a força e adaptabilidade do aço carbono, impulsionando a excelência em diversos setores.',
    'galvanized' => 'GALVANIZADO',
    'galvanizedBody' => 'O aço galvanizado, sinônimo de durabilidade e resistência à corrosão, destaca-se como uma escolha primordial para uma variedade de aplicações. Sua camada de zinco proporciona uma barreira protetora eficaz, garantindo longevidade mesmo em ambientes desafiadores. Descubra a confiabilidade do aço galvanizado, a solução ideal para estruturas robustas e duradouras.',
    'flanges' => 'FLANGES E CONEXÕES',
    'flangesBody' => 'Elevando a solidez das suas operações, nossas flanges e conexões de aço são a escolha definitiva para garantir integridade estrutural e desempenho superior. Projetadas para resistir às demandas industriais mais exigentes, nossas soluções oferecem durabilidade excepcional e precisão milimétrica, assegurando uma conexão confiável em cada aplicação. Descubra a força da qualidade em flanges e conexões de aço, fundamentais para o sucesso contínuo dos seus projetos.',
    'metal' => 'METAL',
    'bronze' => 'BRONZE',
    'bronzeBody' => 'O bronze de engenharia, a fusão perfeita entre força e precisão, é a escolha superior para aplicações industriais exigentes. Reconhecido por sua resistência ao desgaste, corrosão e propriedades de usinagem exemplares, nosso bronze de engenharia oferece soluções robustas para componentes críticos. Descubra o poder da inovação em materiais com o bronze de engenharia, moldando o futuro da excelência industrial.',
    'copper' => 'COBRE',
    'copperBody' => 'O cobre de engenharia, personificação da condução eficiente e durabilidade, destaca-se como a escolha primordial para aplicações elétricas e mecânicas de alta performance. Reconhecido por sua condutividade excepcional e resistência à corrosão, nosso cobre de engenharia oferece soluções confiáveis para os desafios mais exigentes. Descubra a excelência do cobre de engenharia, impulsionando inovação e eficiência em seus projetos.',
    'aluminum' => 'ALUMÍNIO',
    'aluminumBody' => 'O alumínio de engenharia, personificando leveza e resistência, destaca-se como a escolha ideal para inovações em design e durabilidade. Reconhecido por sua versatilidade, nosso alumínio de engenharia oferece soluções excepcionais para aplicações aeroespaciais, automotivas e estruturais. Descubra o potencial ilimitado do alumínio de engenharia, impulsionando a eficiência e performance nos seus projetos.',
    'brass' => 'LATÃO',
    'brassBody' => 'O latão de engenharia, símbolo de versatilidade e resistência, destaca-se como a escolha premium para aplicações que demandam durabilidade e estética refinada. Combinando a durabilidade do cobre e a maleabilidade do zinco, nosso latão de engenharia oferece soluções excepcionais para componentes precisos e elegantes. Descubra a sofisticação e desempenho inigualáveis do latão de engenharia, elevando seus projetos a um novo patamar.',
    'plastic' => 'PLASTICO',
    'teflon' => 'TEFLON',
    'teflonBody' => 'O politetrafluoretileno (PTFE), que é comumente conhecido pelo nome comercial, é sinônimo de resistência excepcional e baixo coeficiente de atrito, destaca-se como a escolha premium para aplicações industriais e tecnológicas exigentes. Com sua capacidade única de resistir a altas temperaturas e substâncias químicas agressivas, nosso teflon de engenharia oferece soluções de ponta para componentes que demandam durabilidade e desempenho superior. Descubra a inovação encapsulada no teflon de engenharia, impulsionando a excelência em engenharia avançada.',
    'pa6g' => 'PA6G',
    'pa6gBody' => 'O nylon fundido PA6G, personificando durabilidade e versatilidade, destaca-se como a escolha robusta para aplicações industriais exigentes. Com propriedades mecânicas excepcionais, nosso nylon fundido oferece resistência ao desgaste, absorção de impactos e estabilidade dimensional, proporcionando soluções de alto desempenho para componentes precisos. Descubra a confiabilidade e inovação encapsuladas no nylon fundido PA6G, impulsionando a excelência em engenharia avançada.',
    'pu' => 'PU',
    'puBody' => 'O poliuretano de engenharia, símbolo de versatilidade e resistência, destaca-se como a escolha inovadora para aplicações que demandam durabilidade e desempenho superior. Com sua adaptabilidade excepcional, nosso poliuretano de engenharia oferece soluções personalizadas para componentes precisos em diversos setores industriais. Descubra a flexibilidade e resistência excepcionais do poliuretano, impulsionando a eficiência e a inovação em seus projetos.',
    'celeron' => 'CELERON',
    'celeronBody' => 'O Celeron de engenharia, sinônimo de resistência elétrica e mecânica, destaca-se como uma escolha premium para isolamento térmico e aplicações elétricas. Com sua composição de fibras impregnadas em resina fenólica, nosso Celeron oferece durabilidade excepcional e estabilidade dimensional, proporcionando soluções confiáveis para ambientes desafiadores. Descubra a inovação e confiabilidade encapsuladas no Celeron de engenharia, impulsionando a excelência em isolamento e componentes elétricos.',
    'rubber' => 'BORRACHA',
    'nbr' => 'NBR',
    'nbrBody' => 'O NBR de engenharia, personificação de resistência e durabilidade, destaca-se como uma escolha premium para aplicações que exigem desempenho excepcional em ambientes desafiadores. Com suas propriedades mecânicas robustas e resistência a diversos fatores ambientais, nosso NBR de engenharia oferece soluções confiáveis para vedação, isolamento e componentes industriais. Descubra a excelência encapsulada no NBR de engenharia, impulsionando a confiabilidade e eficiência em seus projetos.',
    'silicone' => 'SILICONE',
    'siliconeBody' => 'O silicone de engenharia, sinônimo de versatilidade e resistência térmica, destaca-se como a escolha líder para aplicações industriais e médicas. Com propriedades excepcionais de resistência a temperaturas extremas e flexibilidade, nosso silicone de engenharia oferece soluções confiáveis para vedação, isolamento e dispositivos médicos avançados. Descubra a inovação encapsulada no silicone de engenharia, elevando a excelência em design e desempenho.',
    'geomembrane' => 'GEOMEMBRANA',
    'geomembraneBody' => 'A geomembrana de engenharia, símbolo de impermeabilização eficiente e durabilidade, destaca-se como a escolha primordial para projetos geotécnicos e de contenção. Com sua resistência excepcional a agentes químicos e intempéries, nossa geomembrana oferece soluções confiáveis para revestimento de lagoas, aterros sanitários e reservatórios. Descubra a confiança e segurança embutidas na geomembrana de engenharia, impulsionando a qualidade e sustentabilidade em suas aplicações.',
    'neoprene' => 'NEOPRENE',
    'neopreneBody' => 'O neoprene de uso industrial, sinônimo de resistência e versatilidade, destaca-se como a escolha ideal para aplicações exigentes. Com sua durabilidade excepcional e resistência a óleos, solventes e intempéries, nosso neoprene industrial oferece soluções confiáveis para vedação, isolamento e componentes resistentes ao desgaste. Descubra a excelência encapsulada no neoprene de uso industrial, impulsionando a performance e confiabilidade em ambientes industriais',
    'title' => 'STEELPLAST',
    'home' => 'HOME',
    'products' => 'PRODUTOS',
    'about' => 'SOBRE',
    'values' => 'VALORES',
    'contact' => 'CONTATO',
    'language' => 'IDIOMA',
    'aboutBody' => 'Bem-vindo à Steelplast, uma organização dedicada à excelência e à inovação. Desde a nossa fundação em 2000, temos trabalhado incansavelmente para oferecer soluções excepcionais e construir relacionamentos sólidos com nossos clientes, colaboradores e parceiros.',
    'contactBody' => 'Preencha o formulário e retornaremos em breve.',
    'companyValues' => 'Qualidade Intransigente: Comprometemo-nos a oferecer apenas materiais de engenharia que atendam aos mais altos padrões de qualidade, assegurando a satisfação e confiança de nossos clientes.',
    'companyValues2' => 'Inovação Contínua: Estimulamos a criatividade e a busca constante por soluções inovadoras, visando aprimorar nossos processos e antecipar as necessidades do mercado.',
    'companyValues3' => 'Conexão Global: Acreditamos na força das conexões globais e na importância de integrar o Brasil ao cenário internacional, promovendo um intercâmbio de conhecimentos e tecnologias.',
    'companyValues4' => 'Relações de Confiança: Valorizamos a transparência e integridade em todas as nossas relações, cultivando parcerias de longo prazo baseadas na confiança mútua e no respeito.',
    'companyValues5' => 'Atendimento Personalizado: Priorizamos a satisfação do cliente, oferecendo um atendimento personalizado e consultivo, adaptando-nos às necessidades específicas de cada projeto.',
    'toastTime' => 'agora',
    'toastTitle' => 'Oi, eu sou o Steel-bot!',
    'toastBody' => 'Acessando o site, você concorda com as regras de privacidade.',
    'formBtn' => 'Cotação',
    'formQuestion' => 'Sua empresa já faz importação?',
    'formAnswer' => 'Sim, já faço importação!',
    'formAnswer2' => 'Não faço importação!',
    'formResponse' => 'Sentimos muito, mas no momento só atendemos empresas que são habilitadas junto à Receita Federal para importação de materiais.',
    'form' => 'Formulário',
    'close' => 'Fechar',
    'loading' => 'Carregando...',
    'thanks' => 'Obrigado!',
    'error' => 'Ocorreu um erro ao enviar o formulário. Tente novamente mais tarde.',
    'send' => 'Enviar',
    'companyName' => 'Nome da empresa',
    'companyPhone' => 'Telefone da empresa',
    'message' => 'Mensagem',
    'mission' => 'Fornecer soluções de engenharia inovadoras e materiais de alta qualidade, conectando o Brasil ao mundo. Buscamos impulsionar o sucesso de nossos clientes, promovendo a excelência em todos os aspectos de nossas operações.',
    'missionTitle' => 'Nossa Missão',
];

$products = [
    'stainlessSteel' => [
        'workWith' => 'Trabalhamos com o aço Inox 304 e 304L nos seguintes formatos',
        'norms' => 'Normas ASTM A240 e A240M',
        'bars' => 'Diâmetros de 3mm a 200mm por 1 metro e 3 metros.',
        'barsTitle' => 'Barras',
        'tubes' => 'Diâmetros de 6mm a 200mm por 1 metro e 3 metros.',
        'tubesTitle' => 'Tubos',
        'plate' => 'Espessura de 0,40mm a 25,4mm por 1000 x 2000mm e 1000 x 3000mm',
        'plateTitle' => 'Placas',
        'coil' => 'Espessura de 0,30mm a 3mm com largura de 600mm',
        'coilTitle' => 'Bobinas',
    ],
    'carbon' => [
        'workWith' => 'Trabalhamos com o aço carbono 4140, 1045, 1018, 1080 e 1095',
        'norms' => 'Normas ASTM A322, A108, A36, A516 e A106',
        'bars' => 'Espessura de 0,40mm a 25,4mm por 1000 x 2000mm e 1000 x 3000mm',
        'barsTitle' => 'Barras',
        'tubes' => 'Diâmetros de 10,2mm a 400mm por 3 e 6 metros',
        'tubesTitle' => 'Tubos',
        'plate' => 'Espessura de 0,40mm a 25,4mm por 1000 x 2000mm e 1000 x 3000mm',
        'plateTitle' => 'Placas',
        'coil' => 'Espessura de 0,30mm a 5mm com largura de 600mm',
        'coilTitle' => 'Bobinas',
    ],
    'galvanized' => [
        'workWith' => '',
        'norms' => 'Normas ASTM A653/A653M',
        'bars' => 'Diâmetros de 3mm a 200mm por 1 metro e 3 metros.',
        'barsTitle' => 'Barras',
        'tubes' => 'Diâmetros de 12mm a 400mm por 3 e 6 metros',
        'tubesTitle' => 'Tubos',
        'plate' => 'Espessura de 0,40mm a 25,4mm por 1000 x 2000mm e 1000 x 3000mm',
        'plateTitle' => 'Placas',
        'coil' => 'Espessura de 0,30mm a 5mm com largura de 600mm',
        'coilTitle' => 'Bobinas',
    ],
    'flanges' => [
        'workWith' => '',
        'norms' => 'As normas ASTM relacionadas a flanges e conexões de aço variam dependendo do tipo específico e da aplicação. Aqui estão algumas das normas comuns:',
        'normsLoop' => [
            'Flanges de aço carbono: ASTM A105/A105M',
            'Flanges de aço inoxidável: ASTM A182/A182M',
            'Flanges de aço de baixa liga: ASTM A182/A182M',
        ],
        'connections' => [
            'Conexões forjadas de aço carbono e aço de liga: ASTM A105/A105M',
            'Conexões forjadas de aço inoxidável: ASTM A182/A182M',
            'Conexões de tubo de aço carbono e aço de liga: ASTM A234/A234M',
        ],
        'connectionsTitle' => 'Conexões',
    ],  
    'bronze' => [
        'workWith' => '',
        'norms' => 'Normas ASTM B584/584M, B505/B505, SAE J461 e J462',
        'bars' => 'Diametro de 6,35mm a 400mm por 1000mm ou 3000mm.',
        'barsTitle' => 'Barras',
        'tubes' => 'Diametro de 76,20mm a 127mm por 1000mm ou 3000mm.',
        'tubesTitle' => 'Tubos',
        'plate' => 'Espessura de 1,5mm a 3,17mm com largura de 290mm ou 580mm.',
        'plateTitle' => 'Placas',
        'coil' => 'Espessura de 0,10mm a 1,40mm com largura de 290mm ou 580mm.',
        'coilTitle' => 'Bobinas',
    ],
    'copper' => [
        'workWith' => '',
        'norms' => 'Normas ASTM B5/B5M, B187/B187M, B152/B152M e B133/B133M ',
        'bars' => 'Diametro de 3,17mm a 304,80mm por 1000mm ou 3000mmm.',
        'barsTitle' => 'Barras',
        'tubes' => 'Diametro de 76,20mm a 127mm por 1000mm ou 3000mm.',
        'tubesTitle' => 'Tubos',
        'plate' => 'Espessura de 1mm a 3,17mm  por 600 x 1200mm ou 1000 x 2000mm.',
        'plateTitle' => 'Placas',
        'coil' => 'Espessura de 0,10mm a 1,40mm com largura de 305mm ou 600mm.',
        'coilTitle' => 'Bobinas',
    ],
    'aluminum' => [
        'workWith' => '',
        'norms' => 'Normas ASTM B221, B209, AMS 4027',
        'bars' => 'Diametro de  6,35mm a 165,10mm por 1000mm ou 3000mm.',
        'barsTitle' => 'Barras',
        'tubes' => 'Diametro de 9,52mm a 168,28mm por 1000mm ou 3000mm.',
        'tubesTitle' => 'Tubos',
        'plate' => 'Espessura de 5mm a 203,2mm por 1000 x 2000mm ou 1000 x 3000mm.',
        'plateTitle' => 'Placas',
        'coil' => 'Espessura de 0,30mm a 3mm com largura de 305mm ou 600mm.',
        'coilTitle' => 'Bobinas',
    ],
    'brass' => [
        'workWith' => '',
        'norms' => 'Normas ASTM B16, B124, B135/B135M',
        'bars' => 'Diametro de 28,57mm a 203,20mm por 1000mm ou 3000mm.',
        'barsTitle' => 'Barras',
        'tubes' => 'Diamentro 6,35mm a 203,20mm por 1000mm ou 3000mm.',
        'tubesTitle' => 'Tubos',
        'plate' => 'Espessura 3,97mm a 76,20mm de 600mm x 1200mm ou 1000 x 2000mm.',
        'plateTitle' => 'Placas',
        'coil' => 'Espessura de 0,10mm a 3mm por 305mm ou 600mm.',
        'coilTitle' => 'Bobinas',
    ],
    'teflon' => [
        'workWith' => '',
        'norms' => 'Norma ASTM D1710',
        'barsTitle' => 'Barras',
        'bars' => 'Diâmetros de 10mm a 500mm por 1 metro e 3 metros.',
        'tubesTitle' => 'Tubos',
        'tubes' => 'Diâmetros de 50mm a 200mm por 1 metro e 3 metros.',
        'plateTitle' => 'Placas',
        'plate' => 'Espessura de 1 mm a 100mm por 1000 x 1000mm e 1000 x 2000mm.'
    ],
    'pa6g' => [
        'barsTitle' => 'Barras',
        'bars' => 'Diâmetros de 60mm a 500mm por 1000 e 3000mm.',
        'tubesTitle' => 'Tubos',
        'tubes' => 'Diâmetros de 80mm a 200mm por 1000 e 3000mm.',
        'plateTitle' => 'Placas',
        'plate' => 'Espessura de 10 mm a 100mm por 1000 x 2000mm e 1000 x 3000mm'
    ],
    'pu' => [
        'barsTitle' => 'Barras',
        'bars' => 'Diâmetros de 10mm a 300mm por 300mm',
        'tubesTitle' => 'Tubos',
        'tubes' => 'Diâmetros de 50mm a 300mm por 300mm.',
        'plateTitle' => 'Placas',
        'plate' => 'Espessura de 10 mm a 100mm por 500 x 500mm'
    ],
    'celeron' => [
        'barsTitle' => 'Barras',
        'bars' => 'Diâmetros de 6mm a 200mm por 1000mm',
        'tubesTitle' => 'Tubos',
        'tubes' => 'Diâmetros de 9,5mm a 300mm por 1000mm',
        'plateTitle' => 'Placas',
        'plate' => 'Espessura de 0,6 mm a 100mm por 1000 x 2000mm'
    ]
];